- name: "Install packages {{ item }}"
  apt: name={{ item }} update_cache=yes cache_valid_time=36000 state=present
  with_items:
    - apache2
    - php5
    - libapache2-mod-php5
    - php5-mysql
    - curl
  notify: "Restart apache"
