- hosts: ansnode1
  vars_files:
  - ["var_{{ ansible_os_family }}.yml", "var_default.yml"] 
  vars:
    username: Scott
  tasks:
  - debug: msg="Hello {{ username }}!"
  - debug: msg="OS family is  {{ ansible_os_family }}!"
  - debug: msg="picking from file  {{ package_name }}!"
  - command: "service apache2 status"
    register: apache_status
    become: true
  - debug: msg="{{ apache_status }}"
  
