---
- hosts: control
  vars:
    do_token: '50d9590726646810a658335e03abb0bf238db8080684671708af1324f2b444d9'
  tasks:
    - name: ensure key exists
      digital_ocean: >
        state=present
        command=ssh
        name=my_ssh_key
        ssh_pub_key={{ lookup('file','~/.ssh/id_rsa.pub') }}
        api_token={{ do_token }}
      register: my_ssh_key
      
    - name: Print my_ssh_key
      debug: var=my_ssh_key
      
    - name: Create a droplet
      digital_ocean: >
        state=present
        command=droplet
        name=ansible-web
        unique_name=yes
        size_id=512mb
        region_id=sgp1
        image_id=ubuntu-16-04-x64
        ssh_key_ids={{ my_ssh_key.ssh_key.id }}
        api_token={{ do_token }}
      register: droplet_one
    
    - name: Print the details of droplet
      debug: var=droplet_one
      
      
    - name: Add host to our inventory
      add_host:
        name: "{{ droplet_one.droplet.ip_address }}"
        groups: do_webserver
      when: droplet_one.droplet is defined
      
- hosts: do_webserver
  remote_user: root
  gather_facts: no
  tasks:
    - name: Wait for port 22
      local_action: "wait_for port=22 host={{ inventory_hostname }}"

    - name: Wait for port 22
      raw: "apt-get install -y python"

    - name: install apache2
      apt: name=apache2 update_cache=yes cache_valid_time=36000
      
    - name: deploy code
      copy: src=mypage.html dest=/var/www/html/mypage.html
